sudo: required
services:
  - docker

before_install:
  - docker build -t kerz1488/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kerz1488/react-test npm test -- --coverage

after_success:
  - docker build -t kerz1488/multi-client ./client
  - docker build -t kerz1488/multi-nginx ./nginx
  - docker build -t kerz1488/multi-server ./server
  - docker build -t kerz1488/multi-worker ./worker
  # Log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push item to docker hub
  - docker push kerz1488/multi-client
  - docker push kerz1488/multi-nginx
  - docker push kerz1488/multi-server
  - docker push kerz1488/multi-worker


